export interface ChauffClass {
  id: number,
  nom: any,
  prenom: any,
  tele: any,
  gendre: any,
  email: any,
  emplacement: any,
  type_vehicules: any,
  types_paiment: any,
  marque: any,
  model: any,
  annee: any,
  num_serie: any,
  nbr_place: any,
  cout_km: any,
  statut: any,
  colour: any,
  cinNum: any,
  dateCin: any,
  imageCin: any,
  permidate: any,
  numPermis: any,
  imagePermis: any,
  imageAss: any,
  numAss: any,
  dateAss: any,
  imageBadg: any,
  numBadg: any,
  dateBadg: any,
  imageCartCir: any,
  numCartCir: any,
  dateCartCir: any,

}
